# Site settings
title: John Salvie
email: jsalvie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  John Salvie. Dallas, Texas. Software consultant, web developer, designer.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: outofgamut
github_username:  outofgamut

# Build settings
markdown: kramdown


paginate: 10
paginate_path: "blog/page:num"

# Gems
gems: [jekyll-paginate]
